#N BUILTIN EXCEPTIONS MODULE
unknownError='Error tak diketahui'
npyerror={
    "BaseException":unknownError,
    "Exception":unknownError,
    "ArithmeticError":'Kesalahan Aritmatika',
    "FloatingPointError":'Kesalahan Bilangan Desimal',
    "OverflowError":unknownError,
    "ZeroDivisionError":'Kesalahan Pembagian Nol',
    "AssertionError":'Kesalahan Pengecekan',
    "AttributeError":'Kesalahan Atribut',
    "BufferError":unknownError,
    "EOFError":'Kesalahan Akhir Pembacaan Data',
    "ImportError":'Kesalahan Import Pustaka',
    "ModuleNotFoundError":'Pustaka Tak Ditemukan',
    "LookupError":unknownError,
    "IndexError":'Kesalahan Index',
    "KeyError":'Kesalahan Kunci Kamus',
    "MemoryError":'Kesalahan Memori',
    "NameError":'Kesalahan Nama',
    "UnboundLocalError":unknownError,
    "OSError":'Kesalahan Sistem Operasi',
    "BlockingIOError":unknownError,
    "ChildProcessError":unknownError,
    "ConnectionError":'Kesalahan Koneksi',
    "BrokenPipeError":unknownError,
    "ConnectionAbortedError":unknownError,
    "ConnectionRefusedError":unknownError,
    "ConnectionResetError":unknownError,
    "FileExistsError":'File Telah Tersedia',
    "FileNotFoundError":'File Tak Ditemukan',
    "InterruptedError":'Kesalahan Interupsi',
    "IsADirectoryError":unknownError,
    "NotADirectoryError":'Bukan Direktori',
    "PermissionError":'Kesalahan Izin',
    "ProcessLookupError":unknownError,
    "TimeOutError":'Waktu Habis',
    "ReferenceError":'Kesalahan Referensi',
    "RuntimeError":'Kesalahan Saat Menjalankan Program',
    "NotImplementedError":'Tak Diimplementasikan',
    "RecursionError":'Kesalahan Rekursi',
    "StopIteration":'Penghentian Perulangan',
    "StopAsynIteration":unknownError,
    "SyntaxError":'Kesalahan Sintaks',
    "IndentationError":'Kesalahan Identasi',
    "TabError":'Kesalahan Tab',
    "SystemError":'Kesalahan Sistem',
    "TypeError":'Kesalahan Tipe',
    "ValueError":'Kesalahan Nilai',
    "UnicodeError":'Kesalahan Unicode',
    "UnicodeDecodeError":'Kesalahan Unicode(Docode)',
    "UnicodeEncodeError":'Kesalahan Unicode(Encode)',
    "UnicodeTranslateError":'Kesalahan Unicode(Penerjemahan)',
    "Warning":'Peringatan',
    "BytesWarning":'Peringatan Byte',
    "DeprecationWarning":unknownError,
    "FutureWarning":'Peringatan Masa Depan',
    "ImportWarning":'Peringatan Import Pustaka',
    "PendingDeprecationWarning":unknownError,
    "ResourceWarning":'Peringatan SumberDaya',
    "RuntimeWarning":'Peringatan Menjalankan Program',
    "SyntaxWarning":'Peringatan Sintaks',
    "UnicodeWarning":'Peringatan Unicode',
    "UserWarning":'Peringatan Pengguna',
    "GeneratorExit":unknownError,
    "KeyboardInterrupt":'Interupsi Keyboard',
    "SystemExit":'Sistem Keluar',
    "IOError":'Kesalahan IO'
    }
